Pattern("devicesLinkMessage.png").targetOffset(-85,4)
Pattern("devicesLinkMessage.png").targetOffset(630,29)
Pattern("NativescriptLogo.png").targetOffset(330,119)
"appcss.png"
Pattern("Errors.png").similar(0.86)
"ErrorDialogWhenErrorInCode.png"
Pattern("Errors.png").similar(0.86).targetOffset(16,170)
"ErrorsSafari.png"
"angularts.png"
"angulartsSafari.png"
"javascriptjsSafari.png"
"javascriptjs.png"
"typescriptts.png"
"typescripttsSafari.png"
"devicelogs.png"
"devicelogsSafari.png"
"cleardevicelogs.png"
Pattern("devicename.png").targetOffset(-29,39)
Pattern("devicename.png").targetOffset(8,39)
Pattern("devicename.png").targetOffset(194,39)
Pattern("devicename.png").targetOffset(-43,76)
Pattern("model.png").targetOffset(-25,40)
Pattern("model.png").targetOffset(153,39)
Pattern("model.png").targetOffset(82,40)
Pattern("osversion.png").targetOffset(-35,41)
Pattern("osversion.png").targetOffset(75,41)
Pattern("previewappversion.png").targetOffset(-61,38)
Pattern("previewappversion.png").targetOffset(71,38)
Pattern("runtimeversion.png").targetOffset(-52,37)
Pattern("runtimeversion.png").targetOffset(85,37)
"devicestab.png"
"gettingstartedlogo.png"
"closebutton.png"
"okbuttonTutorial.png"
"qrcode.png"
"qrcodeSafari.png"
"ErrorsNotSelected.png"
"playnowbutton.png"
Pattern("home.png").targetOffset(75,88)
"ErrorsNotSelectedSafari.png"
