Pattern("devicesLinkMessage.png").similar(0.63).targetOffset(-101,0)
Pattern("devicesLinkMessage.png").similar(0.63).targetOffset(500,25)
Pattern("NativescriptLogo.png").targetOffset(330,119)
"appcss.png"
Pattern("Errors.png").similar(0.86).targetOffset(-3,16)
"ErrorDialogWhenErrorInCode.png"
Pattern("Errors.png").similar(0.86).targetOffset(16,170)
"angularts.png"
"angulartsSafari.png"
"javascriptjs.png"
"javascriptjsSafari.png"
"typescriptts.png"
"typescripttsSafari.png"
"devicelogs.png"
"cleardevicelogs.png"
Pattern("devicename.png").targetOffset(-29,39)
Pattern("devicename.png").targetOffset(8,39)
Pattern("devicename.png").targetOffset(194,39)
Pattern("devicename.png").targetOffset(-43,76)
Pattern("model.png").targetOffset(-25,40)
Pattern("model.png").targetOffset(153,39)
Pattern("model.png").targetOffset(82,40)
Pattern("osversion.png").targetOffset(-35,41)
Pattern("osversion.png").targetOffset(75,41)
Pattern("previewappversion.png").targetOffset(-61,38)
Pattern("previewappversion.png").targetOffset(71,38)
Pattern("runtimeversion.png").targetOffset(-52,37)
Pattern("runtimeversion.png").targetOffset(85,37)
"devicestab.png"